; comments ignored

[sample.ico]
source=assets/
pack=logo.svg|use laughing-eel
48-rgb=logo.svg|use laughing-eel
32-pal=legacy.bmp|invert #008080|mask #ff00ff
16-bw=small.png

[sample2.ico]
source=assets/
32-true=tray.svg|snip 0,0,12mm,12mm
16-rgb=tray.svg|snip 15mm,0,12mm,12mm

[app.ico]
32-pal=icon.png
16-pal=icon.png